/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package todolistmod;
import java.lang.Object;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.Double;
import java.math.BigDecimal;
import java.math.RoundingMode;
/**
 *
 * @author Martin
 */
public class FileText extends javax.swing.JFrame {

    /**
     * Creates new form FileText
     */
    public FileText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextDisplayScrollPane = new javax.swing.JScrollPane();
        TextFileDisplay = new javax.swing.JTextArea();
        FileName = new javax.swing.JLabel();
        ModifyButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        ProgressDisplay = new javax.swing.JLabel();
        Ca