/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package todolistmod;
import java.lang.Object;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.Double;
import java.math.BigDecimal;
import java.math.RoundingMode;
/**
 *
 * @author Martin
 */
public class FileText extends javax.swing.JFrame {

    /**
     * Creates new form FileText
     */
    public FileText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextDisplayScrollPane = new javax.swing.JScrollPane();
        TextFileDisplay = new javax.swing.JTextArea();
        FileName = new javax.swing.JLabel();
        ModifyButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        ProgressDisplay = new javax.swing.JLabel();
        CalcProgressButton = new javax.swing.JButton();
        ClearListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TextFileDisplay.setEditable(false);
        TextFileDisplay.setBackground(new java.awt.Color(204, 204, 204));
        TextFileDisplay.setColumns(20);
        TextFileDisplay.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        TextFileDisplay.setRows(5);
        TextDisplayScrollPane.setViewportView(TextFileDisplay);

        FileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileName.setText(FileInfo.filename);
        FileName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ModifyButton.setText("Modify List");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Close");
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save File");
        SaveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
       