
package todolistmod;

import java.awt.event.KeyEvent;

public class ToDoListMod extends javax.swing.JFrame {

    /**
     * Creates new form ToDoListMod
     */
    public ToDoListMod() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToDoListMod = new javax.swing.JPanel();
        FileField = new javax.swing.JTextField();
        FileFieldLabel = new javax.swing.JLabel();
        LoadFileButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();